In [10]:
import pandas as pd
import numpy as np

n=300_000
np.random.seed(42)

data={
    "Latitude": np.random.uniform(-90, 90, size=n)
}
print(data["Latitude"])
print(f"size={len(data["Latitude"])}")

[-22.58277861  81.12857515  41.75890953 ...  22.79909934 -81.42301006
  36.73390409]
size=300000


In [12]:
data["Longitude"]=np.random.uniform(-180, 180, size=n)
print(data["Longitude"])
print(f"size={len(data["Longitude"])}")

[-179.26292284 -106.61391156  158.09243036 ...  -27.35454496   95.34128783
  108.70083228]
size=300000


In [17]:
data["Surface_temp_C"]=np.random.normal(loc=-30, scale=20, size=n)
print(data["Surface_temp_C"])
print(f"size={len(data["Surface_temp_C"])}")

[-15.288744   -31.45555083  -4.41550098 ... -36.91172141 -58.68067611
 -12.98864914]
size=300000


In [18]:
data["Pressure_pa"]=np.random.normal(loc=610, scale=50, size=n)
print(data["Pressure_pa"])
print(f"size={len(data["Pressure_pa"])}")

[720.20956183 603.73334034 660.7135982  ... 689.2392213  572.74506002
 546.36266751]
size=300000


In [19]:
data["Gravity_mps2"]=np.full(n, 3.721)
print(data["Gravity_mps2"])
print(f"size={len(data["Gravity_mps2"])}")

[3.721 3.721 3.721 ... 3.721 3.721 3.721]
size=300000


In [22]:
data["Seismic_Amplitude"]=np.random.exponential(scale=0.03, size=n)
print(data["Seismic_Amplitude"])
print(f"size={len(data["Seismic_Amplitude"])}")

[0.0116681  0.06626344 0.00095231 ... 0.02438476 0.00154773 0.00025276]
size=300000


In [23]:
data["Seismic_Frequency_Hz"]=np.random.normal(loc=1.0, scale=0.25, size=n)
print(data["Seismic_Frequency_Hz"])
print(f"size={len(data["Seismic_Frequency_Hz"])}")

[1.17316706 0.77220886 1.00783674 ... 1.07170635 1.41648846 0.71739151]
size=300000


In [24]:
data["Time_Since_Impact_s"]=np.random.exponential(scale=3000, size=n)
print(data["Time_Since_Impact_s"])
print(f"size={len(data["Time_Since_Impact_s"])}")

[ 617.98411405 2444.46589304 3096.80048214 ...  280.90454517 4090.56507911
 5875.91513614]
size=300000


In [25]:
data["Mineral_Density_gcm3"]=np.random.normal(loc=3.5, scale=0.4, size=n)
print(data["Mineral_Density_gcm3"])
print(f"size={len(data["Mineral_Density_gcm3"])}")

[3.23207043 3.58208584 3.07370286 ... 2.96047614 3.81000119 3.80736469]
size=300000


In [26]:
data["Regolith_Depth_m"]=np.random.normal(loc=3.0, scale=2.0, size=n)
print(data["Regolith_Depth_m"])
print(f"size={len(data["Regolith_Depth_m"])}")

[ 4.82253693  4.12531556  3.7232676  ... -0.9165443   4.46473115
 -0.12841625]
size=300000


In [27]:
data["Radiation_mSv"]=np.random.normal(loc=250, scale=40, size=n)
print(data["Radiation_mSv"])
print(f"size={len(data["Radiation_mSv"])}")

[246.66540925 298.53253343 284.64313347 ... 333.29650876 218.43690106
 288.18324768]
size=300000


In [28]:
data["Magnetic_Field_nT"]=np.random.normal(loc=15000, scale=2000, size=n)
print(data["Magnetic_Field_nT"])
print(f"size={len(data["Magnetic_Field_nT"])}")

[15646.96877617 12786.03816451 15621.63920059 ... 14312.68346747
 15274.69078822 14830.26869333]
size=300000


In [29]:
data["Terrain_Type"]=np.random.choice(
            ["Rocky", "Sandy", "Crater", "Volcanic", "Dusty"],
            size=n,
            p=[0.4, 0.2, 0.2, 0.1, 0.1]
        )
print(data["Terrain_Type"])
print(f"size={len(data["Terrain_Type"])}")

['Rocky' 'Crater' 'Volcanic' ... 'Volcanic' 'Rocky' 'Sandy']
size=300000


In [30]:
data["Dust_Content_pct"]=np.random.normal(loc=12, scale=6, size=n)
print(data["Dust_Content_pct"])
print(f"size={len(data["Dust_Content_pct"])}")

[23.28767424 15.18611922 10.70117796 ... 21.26740676 10.95378711
  4.28289451]
size=300000


In [31]:
data["Crater_Age_years"]=np.random.lognormal(mean=12, sigma=1, size=n)
print(data["Crater_Age_years"])
print(f"size={len(data["Crater_Age_years"])}")

[ 164566.30763045  100413.00092072   86591.02272395 ...   84834.10681937
 1695580.88328757 1085602.45741607]
size=300000


In [32]:
data["Solar_Exposure_Wm2"]=np.random.normal(loc=590, scale=70, size=n)
print(data["Solar_Exposure_Wm2"])
print(f"size={len(data["Solar_Exposure_Wm2"])}")

[501.12868622 545.65283406 636.60922412 ... 540.68855793 616.91990893
 469.90870172]
size=300000


In [33]:
data["Surface_Material_Label"]=np.random.choice(
            ["Hematite", "Basalt", "Olivine", "Pyroxene", "Silica", "Sulfates"],
            size=n,
            p=[0.25, 0.25, 0.15, 0.15, 0.1, 0.1]
        )
print(data["Surface_Material_Label"])
print(f"size={len(data["Surface_Material_Label"])}")

['Basalt' 'Basalt' 'Silica' ... 'Hematite' 'Basalt' 'Hematite']
size=300000


In [35]:
print(data.keys())

dict_keys(['Latitude', 'Longitude', 'Surface_temp_C', 'Pressure_pa', 'Gravity_mps2', 'Seismic_Amplitude', 'Seismic_Frequency_Hz', 'Time_Since_Impact_s', 'Mineral_Density_gcm3', 'Regolith_Depth_m', 'Radiation_mSv', 'Magnetic_Field_nT', 'Terrain_Type', 'Dust_Content_pct', 'Crater_Age_years', 'Solar_Exposure_Wm2', 'Surface_Material_Label'])


In [38]:
df=pd.DataFrame(data)
df.to_csv("Mars_data.csv", index=False)
print("mock data maked successfully to Mars_data.csv")

mock data maked successfully to Mars_data.csv
